/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const afterUpdate: typeof import('svelte')['afterUpdate']
  const agent: typeof import('../@tools/useAgent')['agent']
  const beforeUpdate: typeof import('svelte')['beforeUpdate']
  const createEventDispatcher: typeof import('svelte')['createEventDispatcher']
  const echo: typeof import('../@tools/useQuery')['echo']
  const getAllContexts: typeof import('svelte')['getAllContexts']
  const getContext: typeof import('svelte')['getContext']
  const hasContext: typeof import('svelte')['hasContext']
  const inlineStyle: typeof import('../@tools/inlineStyle')['inlineStyle']
  const onDestroy: typeof import('svelte')['onDestroy']
  const onMount: typeof import('svelte')['onMount']
  const setContext: typeof import('svelte')['setContext']
  const style: typeof import('../@tools/useStyle')['style']
  const tick: typeof import('svelte')['tick']
  const useAgent: typeof import('../@tools/useAgent')['useAgent']
  const useMutation: typeof import('../@tools/useQuery')['useMutation']
  const useQuery: typeof import('../@tools/useQuery')['useQuery']
  const useRouteChange: typeof import('../@tools/useRouteChange')['useRouteChange']
  const useStyle: typeof import('../@tools/useStyle')['useStyle']
  const userAgent: typeof import('../@tools/useAgent')['default']
}
