// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const Br: typeof import("./../components/Br.svelte")["default"]
    const CallToAction: typeof import("./../components/CallToAction.svelte")["default"]
    const Feature: typeof import("./../components/Feature.svelte")["default"]
    const Footer: typeof import("./../components/Footer.svelte")["default"]
    const Header: typeof import("./../components/Header.svelte")["default"]
    const Hero: typeof import("./../components/Hero.svelte")["default"]
    const Inquiry: typeof import("./../components/Inquiry.svelte")["default"]
    const Movie: typeof import("./../components/Movie.svelte")["default"]
    const Preloader: typeof import("./../components/Preloader.svelte")["default"]
    const Pricing: typeof import("./../components/Pricing.svelte")["default"]
    const Stats: typeof import("./../components/Stats.svelte")["default"]
    const Usage0: typeof import("./../components/Usage0.svelte")["default"]
    const Usage1: typeof import("./../components/Usage1.svelte")["default"]
    const Usage2: typeof import("./../components/Usage2.svelte")["default"]
    const Usage3: typeof import("./../components/Usage3.svelte")["default"]
    const WrapCenter: typeof import("./../components/WrapCenter.svelte")["default"]
}

export {}
